name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ["latest", "v3.3.0-dev", "v3.2.0", "v3.1.5", "v3.0.8"]
        distro: ["centos:7", "centos:8"]

    env:
      DISTRO: ${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          VERSION=$(echo ${{ matrix.version }} | cut -f -2 -d.)
          docker build . --file Dockerfile --tag docker.pkg.github.com/${{ github.repository }}/${DISTRO/:/-}:$VERSION --build-arg ZEEK_VER=${{ matrix.version }} --build-arg DISTRO=$DISTRO

      - name: Log into registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: github.event_name == 'push'
        run: |
          VERSION=$(echo ${{ matrix.version }} | cut -f -2 -d.)
          docker push docker.pkg.github.com/${{ github.repository }}/${DISTRO/:/-}:$VERSION
