name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: grigorescu/zeek

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ["latest", "v3.3.0-dev", "v3.2.0", "v3.1.5", "v3.0.8"]
        distro: ["centos:7", "centos:8"]

    env:
      DISTRO: ${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME_${DISTRO/:/_}:${{ matrix.version }} --build-arg ZEEK_VER=${{ matrix.version }} --build-arg DISTRO=${{ matrix.distro }}

      - name: Log into registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: github.event_name == 'push'
        run: |
          IMAGE_ID=docker.pkg.github.com/${IMAGE_NAME}_${DISTRO/:/_}

          # Change all uppercase to lowercase and remove the colon
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]' | tr ':' '_')

          echo IMAGE_NAME=$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=${{ matrix.version }}

          docker tag $IMAGE_NAME $IMAGE_ID:${{ matrix.version }}
          docker push $IMAGE_ID:${{ matrix.version }}
