name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: grigorescu/zeek

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        zeek: ["master", "v3.3.0-dev", "v3.2.0", "v3.1.5", "v3.0.8"]
        distro: ["centos:7", "centos:8"]

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg ZEEK_VER=${{ matrix.zeek }} --build-arg DISTRO=${{ matrix.distro }}

      - name: Log into registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: github.event_name == 'push'
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME_${{ matrix.distro }}

          # Change all uppercase to lowercase and remove the semicolon
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]' | tr ':' '_')

          # Strip git ref prefix from version
          VERSION=${{ matrix.zeek }}

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "${{ matrix.zeek }}" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
