name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ["latest", "v3.3.0-dev", "v3.2.0", "v3.1.5", "v3.0.8", "v2.6.4", "v2.5.5", "v2.4.2", "v2.3.2", "v2.2", "v2.1", "v2.0", "v1.5.3", "script_optimizer"]
        distro: ["centos:7", "centos:8", "ubuntu:18.04", "ubuntu:20.04"]

    env:
      DISTRO: ${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          VERSION=$(echo ${{ matrix.version }} | cut -f -2 -d.)
          NAME=$($GITHUB_WORKSPACE/scripts/image_to_tag.sh $DISTRO)
          docker build . --file Dockerfile --tag ${{ github.actor }}/zeek_$NAME:$VERSION --build-arg ZEEK_VER=${{ matrix.version }} --build-arg DISTRO=$DISTRO

      - name: Log into registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: github.event_name == 'push'
        run: |
          VERSION=$(echo ${{ matrix.version }} | cut -f -2 -d.)
          NAME=$($GITHUB_WORKSPACE/scripts/image_to_tag.sh $DISTRO)
          docker push ${{ github.actor }}/zeek_$NAME:$VERSION
