name: Docker Build and Publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  schedule:
    - cron:  '30 7 * * *'
  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ["latest", "v3.3.0-dev", "release/3.2", "release/3.1", "release/3.0", "release/2.6", "script_optimizer"]
        distro: ["centos:7", "centos:8", "ubuntu:18.04", "ubuntu:20.04"]

    env:
      DISTRO: ${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          VERSION=$(echo ${{ matrix.version }} | sed -e 's/.*\///' | cut -f -2 -d.)
          NAME=$($GITHUB_WORKSPACE/scripts/image_to_tag.sh $DISTRO)
          docker build . --file Dockerfile --tag ${{ github.actor }}/zeek_$NAME:$VERSION --build-arg ZEEK_VER=${{ matrix.version }} --build-arg DISTRO=$DISTRO

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          VERSION=$(echo ${{ matrix.version }} | sed -e 's/.*\///' | cut -f -2 -d.)
          NAME=$($GITHUB_WORKSPACE/scripts/image_to_tag.sh $DISTRO)
          docker push ${{ github.actor }}/zeek_$NAME:$VERSION
