name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ["release/2.5", "release/2.4", "release/2.3", "release/2.2", "release/2.1", "release/2.0", "release/1.5"]

    env:
      DISTRO: centos:6

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          VERSION=$(echo ${{ matrix.version }} | sed -e 's/.*\///' | cut -f -2 -d.)
          NAME=$($GITHUB_WORKSPACE/scripts/image_to_tag.sh $DISTRO)
          docker build . --file Dockerfile --tag ${{ github.actor }}/zeek_$NAME:$VERSION --build-arg ZEEK_VER=${{ matrix.version }} --build-arg DISTRO=$DISTRO

      - name: Log into registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: github.event_name == 'push'
        run: |
          VERSION=$(echo ${{ matrix.version }} | cut -f -2 -d.)
          NAME=$($GITHUB_WORKSPACE/scripts/image_to_tag.sh $DISTRO)
          docker push ${{ github.actor }}/zeek_$NAME:$VERSION
